git clone https://github.com/Man4ester/JAVA.git####Man4ester-JAVA
git clone https://github.com/BigStarUa/java.git####BigStarUa-java
git clone https://github.com/Veggid/Java.git####Veggid-Java
git clone https://github.com/atleast/java.git####atleast-java
git clone https://github.com/xianglifeng/java.git####xianglifeng-java
git clone https://github.com/andrew-grechkin/java.git####andrew-grechkin-java
git clone https://github.com/abhijitsarkar/java.git####abhijitsarkar-java
git clone https://github.com/omarhimada/Java.git####omarhimada-Java
git clone https://github.com/quocanha/Java.git####quocanha-Java
git clone https://github.com/NubCoda/Java.git####NubCoda-Java
git clone https://github.com/alen0128/JAVA.git####alen0128-JAVA
git clone https://github.com/luoweipeter/JAVA.git####luoweipeter-JAVA
git clone https://github.com/pureseqgh/java.git####pureseqgh-java
git clone https://github.com/friar/Java.git####friar-Java
git clone https://github.com/zcqmanking/Java.git####zcqmanking-Java
git clone https://github.com/dashynjavolkova/java.git####dashynjavolkova-java
git clone https://github.com/tonysanrusso/Java.git####tonysanrusso-Java
git clone https://github.com/khanhyder/java.git####khanhyder-java
